baseurl = "https://AlyssaStarkLabs.com/"
languageCode = "en-US"
title = "Stark Lab"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
defaultLayout = "/Homepage/"

[permalinks]
   
[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Research"
    url = "/Research/"
[[menu.main]]
    name = "People"
    url = "/people/"
[[menu.main]]
    name = "Perspective Members"
    url = "/Perspective_Members/"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "Stark_Circle.png"
    width = 1000
    height = 1000
    alt = "Stark Labs"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    codeFences = false
